version: "3"

services:
  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    # restart: unless-stopped
    tty: true
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: default
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./volumes/mysql:/var/lib/mysql/
      - ./mysql.cnf:/etc/mysql/my.cnf

#Volumes
# volumes:
#   mysql:
#     driver: local
